FROM rumpcompiler-base-hw

RUN cd /opt && git clone https://github.com/raspberrypi/tools raspberrypi-tools

RUN cd /opt/raspberrypi-tools && \
    mv arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/not-include &&\
    chmod -R a-w  .

COPY __aeabi_ldiv0.c /opt/rumprun/src-netbsd/sys/external/bsd/compiler_rt/dist/lib/builtins/arm/__aeabi_ldiv0.c
COPY __aeabi_idiv0.c /opt/rumprun/src-netbsd/sys/external/bsd/compiler_rt/dist/lib/builtins/arm/__aeabi_idiv0.c
COPY ldcore.S        /opt/rumprun/platform/hw/arch/arm/rpi/locore.S
COPY machdep.c       /opt/rumprun/platform/hw/arch/arm/rpi/machdep.c

RUN cd /opt/rumprun && \
     rm -rf ./obj && \
     git remote add  origin2 https://github.com/dave-tucker/rumprun.git && \
     git fetch origin2 && \
     git checkout raspberrypi && \
     git submodule update


RUN  cd /opt/rumprun && \
     export PATH=/opt/raspberrypi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/:$PATH && \
     export CC=arm-linux-gnueabihf-gcc && \
     ./build-rr.sh -d $DESTDIR -b pi -o ./obj $PLATFORM  build -- -F ACFLAGS=-march=armv6k

RUN  cd /opt/rumprun && \
     export PATH=/opt/raspberrypi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/:$PATH && \
     export CC=arm-linux-gnueabihf-gcc && \
     ./build-rr.sh -d $DESTDIR -o ./obj $PLATFORM install

COPY rumprun-bake.conf /usr/local/etc/rumprun-bake.conf
